### ISSUE TITLE
Temp files not deleted

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip-ilastik#6]
After using the Ilastik headless integration a few times in my workflows (on Windows 7), I observed that there were files (~20GB) getting accumulated in:

    C:\Users\<username>\AppData\Local\Temp\ilastik

The file correspond to the results of the Ilastik Headless node.

I suggest that the [cleanUp](https://github.com/knime-ip/knip-ilastik/blob/master/org.knime.knip.ilastik/src/org/knime/knip/ilastik/nodes/headless/IlastikHeadlessNodeModel.java#L361-L364) either be more rigorous, or complain when it's not possible do delete the temp directory (e.g. due to locked files etc.).

UPDATE:
I tried to delete the directories manually, and it seems that always the last result file still has pointers to it and can't be deleted.

**Comment by dietzc** [comment]
thanks for reporting @imagejan. We will take care about it!

**Comment by gab1one** [comment]
@imagejan I fixed the bug, it should be available in the nightly build tomorrow.
